---
title: peanutButter - A web application to produce rapid-response gridded population estimates from building footprints
output: 
  rmarkdown::html_vignette: 
    toc: true
vignette: >
  %\VignetteIndexEntry{peanutButter - A web application to produce rapid-response gridded population estimates from building footprints}
  %\VignetteEngine{knitr::rmarkdown}
  \usepackage[utf8]{inputenc}
---

22 May 2020

## Overview

The *peanutButter* web application allows you to produce gridded population estimates from building footprints using the "peanut butter" method of spreading people evenly across buildings based on a set of simple parameters. The *peanutButter* application utilizes high resolution maps of building footprints (Ecopia.AI and Maxar Technologies 2020) that are based on recent satellite imagery, to classify each ~100 meter grid cell across a country as 'settled' or 'unsettled'. In all population estimates produced via *peanutButter*, population will be present only in 'settled' grid cells which are those that contain centroid locations of buildings.

The "peanut butter" approach can be applied in a bottom-up or top-down fashion. Bottom-up uses estimates of average household sizes for each settlement type (e.g. urban and rural) and then applies these to each building in the corresponding settlement type. Top-down takes user-defined population totals for administrative units and spreads those people evenly across all buildings within a given unit such that the total per administrative unit matches those defined by the user. The prefered approach will depend on what information you have available: estimates of people per building (bottom-up) or estimates of people per administrative unit (top-down).

Code for the *peanutButter* R package is openly available from WorldPop on GitHub: <a href="https://github.com/wpgp/peanutButter" target="_blank">https://github.com/wpgp/peanutButter</a>.

### Advantages  
- The peanut butter method is quick and easy to implement in situations where detailed population estimates are not currently available.  
- High resolution building footprints provide a valuable source of information about where populations are located and their relative densities.

### Disadvantages
- This method is not objective or driven by population data (i.e. household surveys). It relies on your subjective estimates of population characteristics.  
- There are no estimates of uncertainty provided by this method. You will have no objective basis for determing the accuracy of the estimates produced.  

## Quick Start: Bottom-up
1. Use the sliders to explore population parameters until you find a combination that produces reasonable estimates (shown in the 'Results' table) of total population, urban population, and rural population for the country as a whole. 

2. Adjust the age-sex sliders to select the demographic group(s) that you would like your gridded population estimates to represent. Note: this will not change the population totals shown in the 'Results' table.

3. Use the "Gridded Population Estimates" button to generate a gridded population map (a geotiff raster) that is produced by applying your population parameters to building footprints in each approximately 100 m grid cell across the country.  

4. (optional) Use the "Settings" and/or "Source Files" button(s) to save the input data.

## Quick Start: Top-down
1. Upload a GeoJson file containing polygons and their associated population totals, by clicking on the "Browse" button and selecting your GeoJson file. Ensure that you have the correct country selected.

2. Adjust the age-sex sliders to select the demographic group(s) that you would like your gridded population estimates to represent. 

3. Use the "Gridded Population Estimates" button to generate a gridded population map (a geotiff raster) that is produced by disaggregating a polygon's population total evenly across the buildings inside the polygon.

4. (optional) Use the "Source Files" button to save the input data.


## More Info: Bottom-up

### Method

The peanutButter method requires you to provide estimates of three population characteristics for both urban and rural settlement types using expert opinion:  

1. Mean number of people per housing unit  
2. Mean number of housing units per building  
3. Proportion of buildings that are residential  

Areas have been pre-classified as 'urban' based on two simple rules that are consistent across all countries. A ~100 meter grid cell is classified as 'urban' if it is part of a grouping of contiguous cells with: 1) 1,500 or more cells, and; 2) 5,000 or more buildings (Dooley and Tatem 2020). All grid cells containing building centroids that do not meet the 'urban' criteria, are classified as 'rural'.

The population is estimated using the following formula:  

`Population = Pop_Urban + Pop_Rural`  

`Pop_Urban = Buildings_Urban x PropResidential_Urban x UnitsPerBuilding_Urban x PeoplePerUnit_Urban`  

`Pop_Rural = Buildings_Rural x PropResidential_Rural x UnitsPerBuilding_Rural x PeoplePerUnit_Rural`

You can supply your own inputs (i.e. raster of building count, raster of urban/rural classification) to produce gridded population estimates using the "aggregator" function of the <a href="https://github.com/wpgp/peanutButter" target="_blank">peanutButter</a> R package.

### Population Parameters

**Mean people per housing unit**  
This parameter defines the average number of people in a housing unit and it can be defined for urban and rural areas separately. References for determining these values could include:  

- <a href="https://microdata.worldbank.org/index.php/home" target="_blank">WorldBank Microdata Library</a>  
- <a href="https://www.statcompiler.com/en/" target="_blank">STATCompiler from the DHS Program</a>  
- <a href="https://dhsprogram.com/data/" target="_blank">DHS survey data from USAID</a>  
- <a href="https://mics.unicef.org/surveys" target="_blank">MICS survey data from UNICEF</a>  
- <a href="https://international.ipums.org/international/" target="_blank">IPUMS Census Microdata</a>  
- <a href="https://population.un.org/Household/index.html#/countries/728" target="_blank">United Nations Department of Economic and Social Affairs</a>  

**Mean housing units per building**  
This parameter defines the average number of housing units per residential building. This number would be expected to be near 1 for rural areas and slightly higher in urban areas.

**Proportion residential buildings**  
This parameter defines what proportion of the building counts (Dooley and Tatem 2020) represents residential buildings. Some buildings are non-residential like factories, shops, barns, and sheds. In addition, there are some erroneous building footprints that do not represent buildings and others that may represent more than one building.

### Default Values

We provide moderately informative default values for population parameters, but we strongly urge users to modify the defaults based on a thorough investigation of available data sources. Our process for selecting default values was:  

1. Look up average household sizes (<a href="https://population.un.org/Household/index.html#/countries/728" target="_blank">UN 2019</a> or <a href="https://www.un.org/en/development/desa/population/publications/pdf/ageing/household_size_and_composition_around_the_world_2017_data_booklet.pdf" target="_blank">UN 2017</a>). We assumed that household sizes were equal in urban and rural areas. If no estimate was availabe, we assumed an average of 5 people per housing unit. 

2. Assume there was an average of 1.1 housing units per building in urban areas and 1 housing unit per building in rural areas.  

3. Adjust the proportion of buildings that are residential until the total population matched the <a href="https://data.worldbank.org/indicator/sp.pop.totl" target="_blank">WorldBank estimates</a>, assuming the same proportion of residential buildings for urban and rural areas. For countries where population estimates were available from the <a href="https://wopr.worldpop.org" target="_blank">WorldPop Open Population Repository</a>, we used those total populations instead.

## More Info: Top-down

### Method  

The top-down approach produces gridded population estimates by disaggregating user-provided population totals within user-provided polygon boundaries (e.g. administrative boundaries). There are three steps involved in this process:  

1.  Calculate the total number of buildings in each polygon using the source data from Dooley and Tatem (2020) that were derived from high resolution building footprints (Ecopia.AI and Maxar Technologies 2020).

2. Calculate the average number of people per building by dividing the user-provided population total for each polygon by the total number of buildings in that polygon. 

3. Produce gridded estimates by multiplying the average people per building by the total number of buildings in each ~100 m grid cell.  

User-provided polygons will be ignored if they are too small to overlap the centroid of at least one 100-m grid cell from the building raster (see [Source Data]). If this happens, the total population of the gridded population estimates (i.e. summing all cells) will exclude the populations from these small polygons.

If there are zero buildings within any user-provided polygons, then the gridded population estimates will contain NA for these grid cells.

Areas of your polygons that exceed the national boundaries used in the building footprints (see [Source Data]) will not contain gridded population estimates.

## More Info: Age-sex  

Gridded population estimates for specific demographic group(s) are produced the same way for the top-down and bottom-up methods using ~100 m gridded estimates of the proportion of population in each age-sex group (WorldPop et al. 2018). There are 2 steps involved:  

1. Sum the individual age-sex proportions for each grid cell across the age-sex groups selected using the sliders.  

2. Multiply the resulting grid of proportions by the gridded estimates of total population from the bottom-up or top-down method.

To produce gridded population estimates for specific age-sex groups using your own inputs (i.e. population raster, or region-specific age-sex proportions), you can use the "demographic" function from the <a href="https://github.com/wpgp/peanutButter" target="_blank">peanutButter</a> R package. For an example of the age-sex information needed, please refer to the 'agesex' files downloaded when clicking on the "source files" button for any country.

## Source Data

In the peanutButter app, there are several source datasets working behind the scenes that you can download using the "Download Source" button.  

There are two data sets describing building patterns (Dooley and Tatem 2020) that were derived from building footprints (Ecopia.AI and Maxar Technologies 2020):  

1. The count of buildings in each ~100 m grid cell across the country,  
2. A classification of each ~100 m grid cell as urban or rural.

There are also two source datasets that provide the proportion of population in each demographic group for every ~100 m grid cell (WorldPop et al 2018, Pezullo et al 2017, Carioli et al in prep). The age-sex source files include:  

1. A spreadsheet with age-sex proportions for each region,  
2. A region ID for every 100 m grid cell.  

## Year of Outputs  

The time period associated with gridded population estimates produced by peanutButter depends on several factors. The spatial distribution of the population across the country depends on the spatial distribution of building footprints. The age-sex breakdown depends on the source demographic data. The population totals depend on the population data that you provide. 

**Building footprints**  
The satellite imagery used to create the building footprints is from <a href='http://www.digitalglobe.com/products/mosaics', target='_blank'>Maxar's Vivid imagery mosaics</a>. The exact date depends on the specific satellite image used in the mosaic at a given location. The average mosaic image is less than 20 months old (Ecopia.AI and Maxar Technologies 2020). 

**Demographic data**  
The demographic data (WorldPop et al. 2018) describing age-sex proportions and their spatial distribution are based on projections that represent the year 2020, but they do not account for potential effects of population displacement and migration.

**Population data**  
Bottom-up: The time-point represented by the gridded population estimates is influenced by the date of your settings for "people per housing unit", "housing units per residential building", and "proportion of buildings that are residential". The date reflected by our default values is usually 2018-2019. For more information, refer to our sources described in the sub-section "Default Values" from [More Info: Bottom-up].  

Top-down: The time-point of the gridded population estimates is influenced by the date of the population totals in your uploaded geojson file.  

## Contributing
The _peanutButter_ R package was developed by the WorldPop Research Group within the Department of Geography and Environmental Science at the University of Southampton. Funding was provided by the Bill and Melinda Gates Foundation (INV-002697). Ecopia.AI and Maxar Technologies (2020) provided high resolution building footprints based on recent satellite imagery. Gridded age-sex data were provided by the WorldPop Global High Resolution Population Denominators Project led by Alessandro Sorichetta with funding from the Bill and Melinda Gates Foundation (OPP1134076). Development of the _peanutButter_ R package was led by Doug Leasure. Claire Dooley developed the source rasters of building counts and urban/rural settlements. Maksym Bondarenko maintains WorldPop's Shiny server. Professor Andy Tatem provides oversight of the WorldPop Research Group.   

## Recommended Citation 
Leasure DR, Dooley CA, Bondarenko M, Tatem AJ. 2020. peanutButter: An R package to produce rapid-response gridded population estimates from building footprints, version 0.1.0. WorldPop Research Group, University of Southampton. <a href="https://github.com/wpgp/peanutButter" target="_blank">doi:10.5258/SOTON/WP00667</a>

## License
GNU General Public License v3.0 (GNU GPLv3)  
  
## References  

Carioli A, Pezzulo C, Hanspal S, Hilber T, Hornby G, Kerr D, Tejedor-Garavito N, Nilsen K, Pistolesi L, Adamo S, Mills J, Nieves JJ, Chamberlain H, Bondarenko M, Lloyd C, Ves N, Koper P,  Yetman G, Gaughan A, Stevens F, Linard C, James W, Sorichetta A, and Tatem AJ. In prep. Population structure by age and sex: a multi-temporal subnational perspective.

Ecopia.AI and Maxar Technologies. 2020. Digitize Africa.  

Dooley, C. A. and Tatem, A.J. 2020. Gridded maps of building patterns throughout sub-Saharan Africa, version 1.0. University of Southampton: Southampton, UK. Source of building Footprints "Ecopia Vector Maps Powered by Maxar Satellite Imagery"(C) 2020. https://dx.doi.org/10.5258/SOTON/WP00666  

Pezzulo C, Hornby GM, Sorichetta A, Gaughan AE, Linard C, Bird TJ, Kerr D, Lloyd CT, Tatem AJ. 2017. Sub-national mapping of population pyramids and dependency ratios in Africa and Asia. Sci. Data 4:170089 https://dx.doi.org/10.1038/sdata.2017.89  

WorldPop (www.worldpop.org - School of Geography and Environmental Science, University of Southampton; Department of Geography and Geosciences, University of Louisville; Departement de Geographie, Universite de Namur) and Center for International Earth Science Information Network (CIESIN), Columbia University (2018). Global High Resolution Population Denominators Project - Funded by the Bill and Melinda Gates Foundation (OPP1134076). 

